### ISSUE TITLE
add responsive design

### ISSUE THREAD

**Issue by pradishb** [chamanbravo/upstat#11]
![image](https://github.com/chamanbravo/upstat/assets/17035150/e812aff3-54ac-4a64-a167-8998212b351b)

There is no padding on right and the table is too small in smaller devices.

**Comment by BDFL669** [comment]
Hello, I'd be happy to assist on this issue. Kindly assign it to me :)

**Comment by chamanbravo** [comment]
> Hello, I'd be happy to assist on this issue. Kindly assign it to me :)

hello, thank you for your interest. Please feel free to contribute and create a PR. Your contribution means a lot.

**Comment by BDFL669** [comment]
Thank you, I will do that.
