### ISSUE TITLE
feat: refetch monitors list on delete (frontend)

### ISSUE THREAD

**Issue by chamanbravo** [chamanbravo/upstat#24]
refetch the list of monitors after deleting from the table with delete action

**Comment by jeyren95** [comment]
hey can i take this issue?

**Comment by chamanbravo** [comment]
> hey can i take this issue?

Yeah sure please feel free to contribute. If you encounter any confusion or issues, you can ask or create issues.

**Comment by jeyren95** [comment]
create a PR for this issue [https://github.com/chamanbravo/upstat/pull/27](url)

**Comment by jeyren95** [comment]
i dont see any PR comments, not sure why. Could you maybe send the links to your comments?

**Comment by chamanbravo** [comment]
you should be able to see now.

**Comment by chamanbravo** [comment]
Thank @jeyren95 for your contribution.
