### ISSUE TITLE
feat: support sqlite

### ISSUE THREAD

**Issue by chamanbravo** [chamanbravo/upstat#34]
Sqlite support will make it faster and easier to setup. But don't replace postgres with sqlite. Some might want to add a external database. You can keep both like this.

https://github.com/create-go-app/fiber-go-template/blob/master/platform/database/open_db_connection.go

**Comment by jeyren95** [comment]
hi can i take this?

**Comment by chamanbravo** [comment]
> hi can i take this?

Yeah sure. Please check out the link before adding. Try to keep both sqlite and postgres. Add a new env var db_type, keep sqlite default... And make sure migrations work properly for both. Thank you.

**Comment by jeyren95** [comment]
the current migration script requires creating the pgcrypto extension, but i dont think sqlite has that

are you looking to maintain only 1 migration script for both DB types?

**Comment by chamanbravo** [comment]
yeah, I think having only one migration script would be great.

**Comment by jeyren95** [comment]
hmmm ok i need to dig deeper to see if this is possible

**Comment by chamanbravo** [comment]
we can remove pgcrypto and use crypto library. So the script can work for both.

**Comment by jeyren95** [comment]
ok yeah i guess that works, i'll implement the crypto library in this PR too

**Comment by jeyren95** [comment]
There is another issue with trying to support both postgres and sqlite with the same script:
- Postgres supports the "SERIAL" data type, but sqlite does not, making the id column difficult to synchronize between the postgres and sqlite


Ways that i tried to resolve this but does not work:
1. Using integer primary key autoincrement - does not work because postgres does not support autoincrement
2. Using integer primary key generated always as identity - does not work because not supported by sqlite

**Comment by jeyren95** [comment]
not sure if you might have seen a solution for this somewhere, but we might have to end up having separate scripts if you do want to support both database types

**Comment by jeyren95** [comment]
i am going to try this method of using uuid https://github.com/create-go-app/fiber-go-template/blob/master/platform/migrations/000001_create_init_tables.up.sql 

but do lemme know if you might have seen another solution somewhere else

**Comment by jeyren95** [comment]
im attempting to use UUID as seen in this link https://github.com/create-go-app/fiber-go-template/blob/master/platform/migrations/000001_create_init_tables.up.sql

but do lemme know if you have seen a solution somewhere else

**Comment by chamanbravo** [comment]
Hey thank you for trying, if having a single script for migration doesn't seem possible, we can create different scripts then...

**Comment by jeyren95** [comment]
opened a PR to resolve this issue https://github.com/chamanbravo/upstat/pull/43
