### ISSUE TITLE
feat: add links for notifications & status-pages in cmd menu(frontend)

### ISSUE THREAD

**Issue by chamanbravo** [chamanbravo/upstat#35]
![image](https://github.com/chamanbravo/upstat/assets/76839908/a020da21-33be-474e-9965-61ddae8341d5)

add links for notifications & status-pages

**Comment by jeyren95** [comment]
hi can i take this?

**Comment by chamanbravo** [comment]
> hi can i take this?

Yeah please, I'll assign you the task.

**Comment by jeyren95** [comment]
created a PR here https://github.com/chamanbravo/upstat/pull/39
