### ISSUE TITLE
Creation of the account in loop when I am disconnected

### ISSUE THREAD

**Issue by zarevskaya** [chamanbravo/upstat#47]
Hello,
Since I used docker-compose here: https://github.com/chamanbravo/upstat/issues/46#issuecomment-2273512411

When I log out, I can no longer have the page to log in, it asks me to create an account. 

Any hint? :)

**Comment by chamanbravo** [comment]
Hello, the issue was due to next.js default cache behavior. It has been fixed. Sync it with the latest commit.
Thank you for reporting the issue.

**Comment by zarevskaya** [comment]
Thanks, have a nice day!
