### ISSUE TITLE
Status pages not working

### ISSUE THREAD

**Issue by zarevskaya** [chamanbravo/upstat#48]
Hello,

The status pages not working:

![Screenshot_20240808_105648](https://github.com/user-attachments/assets/df53bebe-b418-46c9-ada7-96a24768de60)

How I can fixe it?

Thanks

**Comment by chamanbravo** [comment]
While migrating to next.js it got left out. Sync with latest commit. 
Thank you for reporting.

**Comment by zarevskaya** [comment]
Thank you very much!

**Comment by zarevskaya** [comment]
I updated everything but I still get a 404 error.

**Comment by chamanbravo** [comment]
Hello are you sure, did you try this `docker compose up -d --build`

**Comment by zarevskaya** [comment]
Yes, I have 2 warnings:

 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 8)
WARN[0000] current commit information was not captured by the build  error="failed to read current commit information with git rev-parse --is-inside-work-tree"

**Comment by zarevskaya** [comment]
I reinstalled everything from scratch and it works.
Thanks :)
