### ISSUE TITLE
Incomplete (docker-compose) installation method?

### ISSUE THREAD

**Issue by zarevskaya** [chamanbravo/upstat#49]
Hello, again!

When I try to install your application with this method:

https://github.com/chamanbravo/upstat#-how-to-install

 I get:

xxxx@xxx:/srv/appdata/upstat$ docker compose up -d
[+] Building 0.2s (1/1) FINISHED                                                                                                                                                                                             docker:default
 => [api internal] load build definition from Dockerfile                                                                                                                                                                               0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                                                     0.0s
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
xxxx@xxxx:/srv/appdata/upstat$ 

Am I at fault?

**Comment by chamanbravo** [comment]
Hey, yeah it's kinda incomplete, I'll let you know when it's complete. Thanks.

**Comment by zarevskaya** [comment]
You'r welcome. Thanks.

**Comment by chamanbravo** [comment]
Hello, the docker installation method in readme is now complete. Do check it out and inform if any issues persist.
Thank you.

**Comment by zarevskaya** [comment]
Work fine, thank you veeeery much! :)
